### ISSUE TITLE
Infinite loop when generate for condition is >= 0

### ISSUE THREAD

**Issue by eddiehung** [YosysHQ/yosys#1118]
## Steps to reproduce the issue

`./yosys backfor.v`

```
module top(output [3:0] o);
generate
    genvar i;
    for (i = 3; i >= 0; i = i-1) begin
        assign o[i] = 1'b0;
    end
endgenerate
endmodule
```

## Expected behavior

No infinite loop.

## Actual behavior

Infinite loop.
Works if condition is `i > 0` (losing one iteration obviously).

**Comment by eddiehung** [comment]
Backtrace:
```
(gdb) bt
#0  _int_malloc (av=av@entry=0x7ffff6882c40 <main_arena>, bytes=bytes@entry=256) at malloc.c:4100
#1  0x00007ffff652e0fc in __GI___libc_malloc (bytes=256) at malloc.c:3057
#2  0x00007ffff7adf258 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                             #3  0x00000000005f6367 in Yosys::AST::AstNode::clone (this=0xfb1780) at frontends/ast/ast.cc:223
#4  0x00000000005f64b3 in Yosys::AST::AstNode::cloneInto (this=0x16d4a020, other=0x16d49b70) at frontends/ast/ast.cc:235
#5  0x0000000000614239 in Yosys::AST::AstNode::expand_genblock (this=<optimized out>, index_var=<incomplete type>, prefix=<incomplete type>,           name_map=std::map with 0 elements) at frontends/ast/simplify.cc:2922
#6  0x0000000000614239 in Yosys::AST::AstNode::expand_genblock (this=<optimized out>, index_var=<incomplete type>, prefix=<incomplete type>,
    name_map=std::map with 0 elements) at frontends/ast/simplify.cc:2922
#7  0x0000000000614239 in Yosys::AST::AstNode::expand_genblock (this=<optimized out>, index_var=<incomplete type>, prefix=<incomplete type>,
    name_map=std::map with 0 elements) at frontends/ast/simplify.cc:2922
#8  0x0000000000614239 in Yosys::AST::AstNode::expand_genblock (this=<optimized out>, index_var=<incomplete type>, prefix=<incomplete type>,
    name_map=std::map with 0 elements) at frontends/ast/simplify.cc:2922
#9  0x0000000000603d67 in Yosys::AST::AstNode::simplify (this=<optimized out>, const_fold=<optimized out>, at_zero=<optimized out>,
    in_lvalue=<optimized out>, stage=<optimized out>, width_hint=<optimized out>, sign_hint=false, in_param=<optimized out>)
    at frontends/ast/simplify.cc:1145
#10 0x0000000000600f18 in Yosys::AST::AstNode::simplify (this=<optimized out>, const_fold=<optimized out>, at_zero=<optimized out>,
    in_lvalue=<optimized out>, stage=<optimized out>, width_hint=<optimized out>, sign_hint=<optimized out>, in_param=<optimized out>)
    at frontends/ast/simplify.cc:699
#11 0x00000000005ff83d in Yosys::AST::AstNode::simplify (this=<optimized out>, const_fold=<optimized out>, at_zero=<optimized out>,
    in_lvalue=<optimized out>, stage=<optimized out>, width_hint=-1, sign_hint=<optimized out>, in_param=<optimized out>)
    at frontends/ast/simplify.cc:76
#12 0x00000000005fa93a in Yosys::process_module (ast=0xfad240, defer=<optimized out>, original_ast=<optimized out>) at frontends/ast/ast.cc:980
<<SNIP>>
```
