### ISSUE TITLE
ABC9/Aiger: Assert `count_id(cell->name) == 0' failed in kernel/rtlil.cc:2027

### ISSUE THREAD

**Issue by q3k** [YosysHQ/yosys#3346]
## Steps to reproduce the issue

Here's the smallest testcase I was able to cobble together. Sorry, it's basically an entire large project - most attempts at minifying it further made the bug not manifest anymore.

```
$ wget https://hackerspace.pl/~q3k/yosys-abc9-aiger-issue.tar.xz
$ tar xf yosys-abc9-aiger-issue.tar.xz
$ cd yosys-abc9-aiger-issue/
$ yosys -s synth.ys
```

## Expected behavior

No crash.

## Actual behavior

```
[...]
20.43.17.5. Executing ABC9.
[...]
20.43.17.6. Executing AIGER frontend.
[...]
ERROR: Assert `count_id(cell->name) == 0' failed in kernel/rtlil.cc:2027.
```

## Preliminary investigation

It seems like the issue is at the post_process stage of the AIGER frontend when loading the result from ABC:

```
#6  0x00005555556d2ee4 in Yosys::RTLIL::Module::add (this=this@entry=0x555562ebb9a0, cell=cell@entry=0x555561699c10) at kernel/rtlil.cc:2027
#7  0x00005555556d305c in Yosys::RTLIL::Module::rename (this=this@entry=0x555562ebb9a0, cell=cell@entry=0x555561699c10, new_name=...) at kernel/rtlil.cc:2125
#8  0x00005555557bcc57 in Yosys::AigerReader::post_process (this=this@entry=0x7fffffffcea8) at frontends/aiger/aigerparse.cc:976
#9  0x00005555557be680 in Yosys::AigerReader::parse_xaiger (this=this@entry=0x7fffffffcea8) at frontends/aiger/aigerparse.cc:518
#10 0x00005555557c2157 in Yosys::AigerFrontend::execute (this=this@entry=0x555555ea6200 <Yosys::AigerFrontend>, f=@0x7fffffffd038: 0x5555575fb1c0, 
```

It seems like when the frontend renames LUTs based on their connected Y wire, it attempts to rename two different cells to the same name. This is after adding some debug log()s:

```
Renaming $lut$aiger244019$22639 to $lut\qf100_frontend.forkDMem_fifoReqRAMA_rv$port1__read[36]
Renaming $lut$aiger244019$26516 to $lut\qf100_frontend.forkDMem_fifoReqRAMA_rv$port1__read[36]
```

I can also reproduce the same error by manually running `read_aiger` against the intermediary files like so:

```
yosys -p 'read_aiger -xaiger -map /tmp/yosys-abc-wPrLSV/input.sym -wideports /tmp/yosys-abc-wPrLSV/output.aig'
```

**Interestingly, disabling `-wideports` causes the error to not manifest.** Commenting out the cell rename loop in post_process also allows the design to synthesize fully (but not sure if correctly).

**Comment by Ravenslofty** [comment]
This does not reproduce with Yosys 0.66 anymore.
